export const genreData = [
  "Fiction",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Non-fiction",
  "Fantasy",
  "Classic",
  "Thriller",
  "Biography",
  "Historical Fiction",
  "Self-help",
  "Horror",
  "Adventure",
  "Young Adult",
  "Dystopian",
  "Contemporary",
  "Poetry",
  "Humor",
  "Graphic Novel",
  "Memoir",
];
